// load the things we need
var mongoose = require("mongoose");

var devicesSchema = mongoose.Schema({

  type: String,
  brand: String,
  features:[{
    model: String,
  year: Number,
  clinicalapp: String,
  pic: String,
  diffrent: String,
  mechanic: String,
  annular: String,
  linear: String,
  convex: String,
  phased: String,
  multifq: String,
  endovaginal: String,
  endorectal: String,
  other: String,
  framerate: String,
  grayscale: Number,
  preprocess: String,
  postprocess: String,
  dispdepth: Number,
  mmode: Boolean,
  mmode2d: Boolean,
  a3d: Boolean,
  a4d: Boolean,
  harmonicimaging: Boolean,
  dopplertype: String,
  fqdisp: Boolean,
  veldisp: Boolean,
  power: Boolean,
  duplex: Boolean,
  triplex: Boolean,
  digital: Boolean,
  selectable: Boolean,
  adjustable: Boolean,
  dynamicrec: Boolean,
  measurements: Boolean,
  rtimg: Boolean,
  freez: Boolean,
  capacity: Number,
  cine: String,
  dicom: Boolean,
  pacs: Boolean,
  cardiac: String,
  vasc: Boolean,
  ob: Boolean,
  others: Boolean,
  progprot: String,
  userprog: Boolean,
  transrec: Boolean,
  transperineal: Boolean,
  monitor: String,
  split: Boolean,
  power: String,
  battery: String,
  hwd: String,
  weight: Number,
  warr: String
}]
});

module.exports = mongoose.model("Devices", devicesSchema);
